In [106]:
import pandas as pd
import numpy as np
import math
import sys
data=[]

In [109]:
# line_number = 7  # Example: Read the third line
data=[]        
line_number = sys.maxsize

with open('./ali535.tsp', 'r') as file:
    for idx, line in enumerate(file):
        if "DIMENSION"in line:
            print(f"Node number: {line.split()[1]}")
        if "NODE_COORD_SECTION" in line:
            line_number = idx
        elif idx >= line_number - 1:
            data.append(line.split())
df = pd.DataFrame(data, columns=['No.', 'x', 'y'])
df.set_index('No.', inplace=True)

def ElurDist(xx,yy):
    xx,yy =float(xx),float(yy)
    result = math.sqrt(abs(xx-yy))
    return np.round(result,3)

for idx in range(df.shape[0]):
    xx,yy = df.iloc[idx][0],df.iloc[idx][1]
    if df.iloc[idx][0] is not None:
        s = ElurDist(xx,yy)
        print(f"{idx}: {s}")


Node number: 535
0: 5.385
1: 6.896
2: 4.233
3: 2.951
4: 11.873
5: 7.697
6: 10.766
7: 2.337
8: 6.475
9: 5.467
10: 5.703
11: 13.148
12: 6.29
13: 6.608
14: 6.38
15: 5.675
16: 6.214
17: 5.751
18: 14.542
19: 6.206
20: 5.77
21: 1.015
22: 11.686
23: 2.002
24: 6.908
25: 14.515
26: 2.676
27: 6.843
28: 8.863
29: 5.491
30: 2.373
31: 6.468
32: 4.834
33: 5.672
34: 2.982
35: 3.755
36: 10.852
37: 9.072
38: 5.479
39: 2.464
40: 4.921
41: 3.118
42: 10.748
43: 9.22
44: 6.016
45: 5.896
46: 6.255
47: 9.831
48: 10.676
49: 4.777
50: 4.93
51: 5.01
52: 3.45
53: 6.249
54: 7.247
55: 4.789
56: 1.342
57: 7.78
58: 11.692
59: 3.751
60: 8.505
61: 7.419
62: 10.629
63: 3.317
64: 6.013
65: 10.945
66: 7.329
67: 5.748
68: 12.404
69: 6.678
70: 5.442
71: 5.69
72: 9.317
73: 4.517
74: 6.808
75: 5.757
76: 8.052
77: 7.07
78: 5.394
79: 13.428
80: 6.703
81: 8.861
82: 7.21
83: 7.312
84: 7.276
85: 10.64
86: 6.675
87: 4.961
88: 6.265
89: 7.325
90: 6.801
91: 5.66
92: 6.327
93: 5.654
94: 5.303
95: 4.882
96: 10.997
97: 4.271
98: 6.87
9

In [82]:
type(df.iloc[-1][0])

NoneType

In [68]:
df.iloc[19]

x    148
y    145
Name: 20, dtype: object

In [129]:
a = set([idx for idx in range(1,20)])
a

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19}

In [137]:
import random
random.randint(1,10)

9

In [193]:
def Generate(node=10):
    sol=[]
    NotVisited = set(range(1, node + 1))

    # Initial
    StartPoint = random.choice(list(NotVisited))
    sol.append(StartPoint)
    NotVisited.remove(StartPoint)
    # print(f"StartPoint: {StartPoint}")
    
    # Find subsequent
    while NotVisited:
        NextPoint = NotVisited.pop()
        sol.append(NextPoint)
    # print(sol)
    return sol #[1,4,2,5,10,3,...]

In [194]:
def GenerateDisMat(node):
    M = np.zeros((node,node),dtype=int)
    for i in range(node):
        for j in range(node):
            value = np.random.randint(0,10)
            M[i][j] =M[j][i] = value
            M[i][i] = 0
    return M

GenerateDisMat(5)

array([[0, 4, 2, 1, 5],
       [4, 0, 8, 5, 4],
       [2, 8, 0, 6, 1],
       [1, 5, 6, 0, 8],
       [5, 4, 1, 8, 0]])

In [211]:
a = GenerateDisMat(node=5)
def EdgeCost(DistMatrix,p1,p2):
    return DistMatrix[p1-1][p2-1]


In [215]:
sol =[]
node =5
AntNum  =5
for idx in range(AntNum):
    tmp = Generate(node)
    sol.append(tmp)
    Cost=0
    for s in range(node-1):
        Cost += EdgeCost(a,tmp[s],tmp[s+1])
        s+=2
    print(f"No.{idx}: {Cost}")

No.0: 11
No.1: 5
No.2: 11
No.3: 5
No.4: 7


In [7]:
[i+1 for i in range(5)]

[1, 2, 3, 4, 5]

In [213]:
a 
# 8 5 4 7
# 8 5 

array([[0, 5, 0, 8, 9],
       [5, 0, 4, 0, 0],
       [0, 4, 0, 2, 7],
       [8, 0, 2, 0, 0],
       [9, 0, 7, 0, 0]])

In [191]:
for idx in range(5):
    Cost = 0
    for s in range(len(sol[idx])-1):
        p1 = sol[idx][s-1]
        p2 = sol[idx][s]
        Cost += EdgeCost(p1,p2)
    print(Cost)
    # break

87
63
78
96
79


In [15]:
import random
sol = []
NotVisited = [i + 1 for i in range(5)]
print(NotVisited)

# Initial point(by random pick)
StartPoint = random.choice(NotVisited)
NotVisited.remove(StartPoint)
print(NotVisited)
sol.append(StartPoint)

# Finish the subsequent solution
while len(NotVisited) != 0:
    pick = random.choice(NotVisited)
    NotVisited.remove(pick)
    sol.append(pick)
print(sol)


[1, 2, 3, 4, 5]
[1, 2, 3, 4]
[5, 2, 4, 1, 3]


In [22]:
node =20
sol=[]
NotVisited = list(range(1, node + 1))
random.shuffle(NotVisited)
sol.extend(NotVisited)
print(sol)

[19, 15, 2, 9, 13, 7, 8, 14, 3, 6, 5, 1, 20, 16, 4, 10, 12, 18, 11, 17]


In [63]:
db=[[1,2,3],[3,2,1],[1,3,2]]

In [78]:
def DeltaSum(i, j, db):
    for ant_idx, ant in enumerate(db):
        if i in ant and i != ant[-1] and ant[ant.index(i) + 1] == j:
            print(f"Yes {ant_idx}")
        else:
            print(f"Not found in ant {ant_idx}")

In [79]:
DeltaSum(3,2,db)

Not found in ant 0
Yes 1
Yes 2


In [83]:
import numpy as np
def RandSquareMat(min, max, dim):
        """Random Generate distance cost matrix
        for debug use"""
        M = np.zeros((dim, dim), dtype=float)
        for i in range(dim):
            for j in range(dim):
                M[i][j] = M[j][i] = random.uniform(min, max)
                M[i][i] = 0
        return M

In [146]:
PheronomeMatrix, DistMatrix = RandSquareMat(1.0,10,dim=4),RandSquareMat(1.0,100,dim=4)
print(PheronomeMatrix)
print(DistMatrix)

[[0.         6.0598815  1.11833681 8.11583047]
 [6.0598815  0.         4.85104941 3.90540768]
 [1.11833681 4.85104941 0.         1.81868511]
 [8.11583047 3.90540768 1.81868511 0.        ]]
[[ 0.         60.65153151 45.15517926 23.95946152]
 [60.65153151  0.         85.71215904 98.09045155]
 [45.15517926 85.71215904  0.         14.39093328]
 [23.95946152 98.09045155 14.39093328  0.        ]]


In [150]:
NodeNum =4
alpha = beta =1
def SolConstruct():
        """Solution constuct in single ant"""
        visited = []
        unvistied = list(range(NodeNum))
        # print(unvistied)

        StartPoint = random.randint(0, NodeNum)
        visited.append(StartPoint)
        unvistied.remove(StartPoint)
        # print(unvistied)


        while len(visited) != NodeNum:
            # Calculate the probability of next point
            prob = np.zeros(len(unvistied), dtype=float)
            for idx, u_idx in enumerate(unvistied):
                prob[idx] = NextPointProb(visited[-1], u_idx, visited,PheronomeMatrix, DistMatrix)
            print(prob)
            total_prob = sum(prob)
            normalized_probs = [p / total_prob for p in prob]

            # Pick next point porportion to the prob calcluate in the above
            next_point = np.random.choice(unvistied, p=normalized_probs)
            visited.append(next_point)
            unvistied.remove(next_point)
        
        print(visited)
        return visited

def NextPointProb(i, j, visited, PheronomeMatrix, DistMatrix):
        P, _D = PheronomeMatrix, np.where(DistMatrix != 0, 1 / DistMatrix, 0)
        dd = 0
        uu = (P[i][j]) ** alpha + (_D[i][j]) ** beta
        for v in visited:
            dd += (P[i][v]) ** alpha + (_D[i][v]) ** beta
        
        # Add a small constant to avoid division by zero
        epsilon = 1e-10
        dd += epsilon
            
        prob = uu / dd
        return prob

In [151]:
SolConstruct()

[1.14048267e+10 4.86271636e+10 1.88817331e+10]
[1.24958329 0.80522943]
[1.13034989]
[2, 1, 0, 3]


/var/folders/1z/by3dhv6x3fsfqlxysgxnx1y80000gn/T/ipykernel_99552/1767458126.py:33: RuntimeWarning: divide by zero encountered in divide
  P, _D = PheronomeMatrix, np.where(DistMatrix != 0, 1 / DistMatrix, 0)


[2, 1, 0, 3]

In [163]:
a = [10,1,3,4]
aa = np.sort(a)[::-1][:2]
aa

array([10,  4])

In [164]:
[a.index(i) for i in aa]

[0, 3]

In [165]:
import glob
import contextlib
from PIL import Image

# filepaths
fp_in = "/Users/samchen/Pictures/2023/cs/Export/*.jpg"
fp_out = "/Users/samchen/Desktop/image.gif"

# use exit stack to automatically close opened images
with contextlib.ExitStack() as stack:

    # lazily load images
    imgs = (stack.enter_context(Image.open(f))
            for f in sorted(glob.glob(fp_in)))

    # extract  first image from iterator
    img = next(imgs)

    # https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html#gif
    img.save(fp=fp_out, format='GIF', append_images=imgs,
             save_all=True, duration=100, loop=0)
